import type { MovieRecord } from "@/schemas/record/record";

type MockInput = Omit<MovieRecord, "createdAt" | "updatedAt" | "recordId">;

function mock(id: number, input: MockInput): MovieRecord {
  const createdAt = new Date(input.watchedAt);
  createdAt.setUTCHours(createdAt.getUTCHours() + 2);
  return {
    recordId: String(id),
    ...input,
    createdAt: createdAt.toISOString(),
    updatedAt: createdAt.toISOString(),
  };
}

export const mockRecords: MovieRecord[] = [
  mock(1, {
    title: "ドライブ・マイ・カー",
    releaseYear: 2021,
    runtime: 179,
    genres: ["drama"],
    countries: ["JP"],
    language: "ja",
    credits: [
      { creditRole: "director", personName: "濱口竜介" },
      { creditRole: "writer", personName: "濱口竜介" },
      { creditRole: "writer", personName: "大江崇允" },
      { creditRole: "cinematographer", personName: "四宮秀俊" },
      { creditRole: "composer", personName: "石橋英子" },
      { creditRole: "cast", personName: "西島秀俊" },
      { creditRole: "cast", personName: "三浦透子" },
      { creditRole: "cast", personName: "霧島れいか" },
    ],
    posterUrl: "",
    watchedAt: "2026-08-16T13:00:00Z",
    platform: "netflix",
    score: 5,
    moodTags: ["poignant", "minimal"],
    memo: "車内の会話だけで関係が変わっていくのがよかった。長さは気にならない。終盤の雪の場面で、ずっと黙っていた人がやっと喋る、その順番が正しく感じられた。もう一度みるなら字幕の芝居のところを注意して観たい。",
  }),
  mock(2, {
    title: "パターソン",
    releaseYear: 2016,
    runtime: 118,
    genres: ["drama", "comedy"],
    countries: ["US"],
    language: "en",
    credits: [
      { creditRole: "director", personName: "ジム・ジャームッシュ" },
      { creditRole: "cast", personName: "アダム・ドライバー" },
    ],
    posterUrl: "",
    watchedAt: "2026-08-14T12:00:00Z",
    platform: "u_next",
    score: 4,
    moodTags: ["cozy", "minimal"],
    memo: "毎日が同じようで少しずつ違う。詩のノートの場面が好き。",
  }),
  mock(3, {
    title: "東京物語",
    releaseYear: 1953,
    runtime: 136,
    genres: ["drama", "family"],
    countries: ["JP"],
    language: "ja",
    credits: [
      { creditRole: "director", personName: "小津安二郎" },
      { creditRole: "cast", personName: "笠智衆" },
      { creditRole: "cast", personName: "原節子" },
    ],
    posterUrl: "",
    watchedAt: "2026-08-09T11:00:00Z",
    platform: "criterion_channel",
    score: 5,
    moodTags: ["nostalgic", "poignant"],
    memo: "",
  }),
  mock(4, {
    title: "花様年華",
    releaseYear: 2000,
    runtime: 98,
    genres: ["drama", "romance"],
    countries: ["HK", "FR"],
    language: "zh",
    credits: [
      { creditRole: "director", personName: "ウォン・カーウァイ" },
      { creditRole: "cast", personName: "トニー・レオン" },
      { creditRole: "cast", personName: "マギー・チャン" },
    ],
    posterUrl: "",
    watchedAt: "2026-08-03T14:00:00Z",
    platform: "mubi",
    score: 4,
    moodTags: ["stylish", "poignant", "romantic"],
    memo: "色と音楽だけで成立している。",
  }),
  mock(5, {
    title: "マッドマックス 怒りのデス・ロード",
    releaseYear: 2015,
    runtime: 120,
    genres: ["action", "adventure", "science_fiction"],
    countries: ["AU", "US"],
    language: "en",
    credits: [{ creditRole: "director", personName: "ジョージ・ミラー" }],
    posterUrl: "",
    watchedAt: "2026-07-27T12:00:00Z",
    platform: "theater",
    score: 5,
    moodTags: ["refreshing", "epic"],
    memo: "リバイバル上映。音が大きいほどいい映画。",
  }),
  mock(6, {
    title: "パラサイト 半地下の家族",
    releaseYear: 2019,
    runtime: 132,
    genres: ["thriller", "drama", "comedy"],
    countries: ["KR"],
    language: "ko",
    credits: [{ creditRole: "director", personName: "ポン・ジュノ" }],
    posterUrl: "",
    watchedAt: "2026-07-20T13:00:00Z",
    platform: "amazon_prime_video",
    score: 4,
    moodTags: ["tense", "dark"],
    memo: "",
  }),
  mock(7, {
    title: "千と千尋の神隠し",
    releaseYear: 2001,
    runtime: 125,
    genres: ["animation", "fantasy", "family"],
    countries: ["JP"],
    language: "ja",
    credits: [
      { creditRole: "director", personName: "宮崎駿" },
      { creditRole: "composer", personName: "久石譲" },
    ],
    posterUrl: "",
    watchedAt: "2026-07-12T10:00:00Z",
    platform: "tv_broadcast",
    score: 4,
    moodTags: ["nostalgic", "heartwarming"],
    memo: "何度目か分からない。",
  }),
  mock(8, {
    title: "セッション",
    releaseYear: 2014,
    runtime: 107,
    genres: ["drama", "music"],
    countries: ["US"],
    language: "en",
    credits: [{ creditRole: "director", personName: "デイミアン・チャゼル" }],
    posterUrl: "",
    watchedAt: "2026-07-05T12:00:00Z",
    platform: "netflix",
    score: 3,
    moodTags: ["tense"],
    memo: "",
  }),
  mock(9, {
    title: "ムーンライト",
    releaseYear: 2016,
    runtime: 111,
    genres: ["drama"],
    countries: ["US"],
    language: "en",
    credits: [{ creditRole: "director", personName: "バリー・ジェンキンス" }],
    posterUrl: "",
    watchedAt: "2026-06-28T12:00:00Z",
    platform: "u_next",
    score: 4,
    moodTags: ["poignant", "minimal"],
    memo: "",
  }),
  mock(10, {
    title: "ゲット・アウト",
    releaseYear: 2017,
    runtime: 104,
    genres: ["horror", "mystery", "thriller"],
    countries: ["US"],
    language: "en",
    credits: [{ creditRole: "director", personName: "ジョーダン・ピール" }],
    posterUrl: "",
    watchedAt: "2026-06-21T13:00:00Z",
    platform: "netflix",
    score: 3,
    moodTags: ["disturbing", "tense"],
    memo: "",
  }),
  mock(11, {
    title: "ショーシャンクの空に",
    releaseYear: 1994,
    runtime: 142,
    genres: ["drama", "crime"],
    countries: ["US"],
    language: "en",
    credits: [{ creditRole: "director", personName: "フランク・ダラボン" }],
    posterUrl: "",
    watchedAt: "2026-06-14T12:00:00Z",
    platform: "dvd_bluray",
    score: 5,
    moodTags: ["moving", "heartwarming"],
    memo: "",
  }),
  mock(12, {
    title: "ラ・ラ・ランド",
    releaseYear: 2016,
    runtime: 128,
    genres: ["romance", "music", "drama"],
    countries: ["US"],
    language: "en",
    credits: [{ creditRole: "director", personName: "デイミアン・チャゼル" }],
    posterUrl: "",
    watchedAt: "2026-06-07T12:00:00Z",
    platform: "amazon_prime_video",
    score: 3,
    moodTags: ["romantic", "bitter_ending"],
    memo: "",
  }),
  mock(13, {
    title: "ノマドランド",
    releaseYear: 2020,
    runtime: 108,
    genres: ["drama"],
    countries: ["US"],
    language: "en",
    credits: [{ creditRole: "director", personName: "クロエ・ジャオ" }],
    posterUrl: "",
    watchedAt: "2026-05-30T12:00:00Z",
    platform: "disney_plus",
    score: 4,
    moodTags: ["minimal", "poignant"],
    memo: "",
  }),
  mock(14, {
    title: "エブリシング・エブリウェア・オール・アット・ワンス",
    releaseYear: 2022,
    runtime: 139,
    genres: ["action", "comedy", "science_fiction"],
    countries: ["US"],
    language: "en",
    credits: [
      { creditRole: "director", personName: "ダニエル・クワン" },
      { creditRole: "director", personName: "ダニエル・シャイナート" },
    ],
    posterUrl: "",
    watchedAt: "2026-05-24T12:00:00Z",
    platform: "u_next",
    score: 4,
    moodTags: ["absurd", "moving"],
    memo: "",
  }),
  mock(15, {
    title: "ゴッドファーザー",
    releaseYear: 1972,
    runtime: 175,
    genres: ["crime", "drama"],
    countries: ["US"],
    language: "en",
    credits: [
      { creditRole: "director", personName: "フランシス・フォード・コッポラ" },
    ],
    posterUrl: "",
    watchedAt: "2026-05-17T12:00:00Z",
    platform: "rental",
    score: 5,
    moodTags: ["hardboiled", "epic"],
    memo: "",
  }),
  mock(16, {
    title: "君の名は。",
    releaseYear: 2016,
    runtime: 107,
    genres: ["animation", "romance", "fantasy"],
    countries: ["JP"],
    language: "ja",
    credits: [{ creditRole: "director", personName: "新海誠" }],
    posterUrl: "",
    watchedAt: "2026-05-10T12:00:00Z",
    platform: "abema",
    score: 3,
    moodTags: ["romantic", "refreshing"],
    memo: "",
  }),
  mock(17, {
    title: "メッセージ",
    releaseYear: 2016,
    runtime: 116,
    genres: ["science_fiction", "drama", "mystery"],
    countries: ["US"],
    language: "en",
    credits: [{ creditRole: "director", personName: "ドゥニ・ヴィルヌーヴ" }],
    posterUrl: "",
    watchedAt: "2026-05-03T12:00:00Z",
    platform: "netflix",
    score: 4,
    moodTags: ["poignant", "surreal"],
    memo: "",
  }),
  mock(18, {
    title: "万引き家族",
    releaseYear: 2018,
    runtime: 121,
    genres: ["drama", "crime"],
    countries: ["JP"],
    language: "ja",
    credits: [{ creditRole: "director", personName: "是枝裕和" }],
    posterUrl: "",
    watchedAt: "2026-04-26T12:00:00Z",
    platform: "hulu",
    score: 4,
    moodTags: ["poignant", "bitter_ending"],
    memo: "",
  }),
  mock(19, {
    title: "グランド・ブダペスト・ホテル",
    releaseYear: 2014,
    runtime: 99,
    genres: ["comedy", "adventure"],
    countries: ["US", "DE"],
    language: "en",
    credits: [{ creditRole: "director", personName: "ウェス・アンダーソン" }],
    posterUrl: "",
    watchedAt: "2026-04-19T12:00:00Z",
    platform: "disney_plus",
    score: 3,
    moodTags: ["stylish", "absurd"],
    memo: "",
  }),
  mock(20, {
    title: "ヘレディタリー／継承",
    releaseYear: 2018,
    runtime: 127,
    genres: ["horror", "mystery"],
    countries: ["US"],
    language: "en",
    credits: [{ creditRole: "director", personName: "アリ・アスター" }],
    posterUrl: "",
    watchedAt: "2026-04-12T13:00:00Z",
    platform: "u_next",
    score: 2,
    moodTags: ["disturbing", "dark"],
    memo: "",
  }),
  mock(21, {
    title: "カメラを止めるな！",
    releaseYear: 2017,
    runtime: 96,
    genres: ["comedy", "horror"],
    countries: ["JP"],
    language: "ja",
    credits: [{ creditRole: "director", personName: "上田慎一郎" }],
    posterUrl: "",
    watchedAt: "2026-04-05T12:00:00Z",
    platform: "amazon_prime_video",
    score: 4,
    moodTags: ["refreshing", "absurd"],
    memo: "",
  }),
  mock(22, {
    title: "ブレードランナー 2049",
    releaseYear: 2017,
    runtime: 163,
    genres: ["science_fiction", "drama"],
    countries: ["US"],
    language: "en",
    credits: [{ creditRole: "director", personName: "ドゥニ・ヴィルヌーヴ" }],
    posterUrl: "",
    watchedAt: "2026-03-29T12:00:00Z",
    platform: "netflix",
    score: 3,
    moodTags: ["stylish", "dark"],
    memo: "",
  }),
  mock(23, {
    title: "アメリ",
    releaseYear: 2001,
    runtime: 122,
    genres: ["comedy", "romance"],
    countries: ["FR"],
    language: "fr",
    credits: [
      { creditRole: "director", personName: "ジャン＝ピエール・ジュネ" },
    ],
    posterUrl: "",
    watchedAt: "2026-03-22T12:00:00Z",
    platform: "mubi",
    score: 3,
    moodTags: ["cozy", "romantic"],
    memo: "",
  }),
  mock(24, {
    title: "2001年宇宙の旅",
    releaseYear: 1968,
    runtime: 149,
    genres: ["science_fiction", "adventure"],
    countries: ["US", "GB"],
    language: "en",
    credits: [
      { creditRole: "director", personName: "スタンリー・キューブリック" },
    ],
    posterUrl: "",
    watchedAt: "2026-03-15T12:00:00Z",
    platform: "theater",
    score: 5,
    moodTags: ["epic", "experimental"],
    memo: "",
  }),
];
